# Simple workflow for deploying Streamlit app to GitHub Pages
name: Deploy Streamlit app to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-streamlit:
    name: Deploy Streamlit app
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Streamlit
        run: pip install streamlit
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          branch: gh-pages
          publish_dir: ./recsys_app
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      # Output the URL of the deployed GitHub Pages site
      - name: Output Deployed URL
        run: |
          echo "Deployed URL: ${{ steps.deployment.outputs.page_url }}"
